name = "gramio-forum-bot"
main = "src/index.ts"
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[vars]
# Non-sensitive variables can go here
# Sensitive ones should be added via `wrangler secret put`
