name = "gramio-forum-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Non-sensitive variables can go here
# Sensitive ones should be added via `wrangler secret put`
